# Generated by Django 5.0.6 on 2025-05-11 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
