# Generated by Django 5.0.6 on 2025-05-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_appointment_schedule_remove_appointment_date_and_more'),
        ('core', '0003_staffuser'),
    ]

    operations = [
    ]
