# Generated by Django 5.2 on 2025-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250516_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
