# Generated by Django 5.2 on 2025-05-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_confirmada'),
        ('core', '0005_invoice'),
    ]

    operations = [
    ]
